using NUnit.Framework;
using RimWorld_LanguageWorker_Spanish;
using System;
using System.Collections.Generic;

namespace RimWorldLanguageWorkerSpanish_NUnitTest
{
	public class TestPluralize
	{
		[Test()]
		public void TestPluralization()
		{
			LanguageWorker_Spanish _lw = new LanguageWorker_Spanish();

			// Almost all labels in the game (why not?)
			Dictionary<string, string> labels = new Dictionary<string, string>
			{
				{"acier","aciers"},
				{"activateur de compte à rebours","activateurs de compte à rebours"},
				{"activateur de guérison","activateurs de guérison"},
				{"activateur de proximité","activateurs de proximité"},
				{"activateur d'immunité","activateurs d'immunité"},
				{"addiction à l'alcool","addictions à l'alcool"},
				{"addiction à l'ambroisie","addictions à l'ambroisie"},
				{"addiction au go-juice","addictions au go-juice"},
				{"addiction au smokeleaf","addictions au smokeleaf"},
				{"addiction au wake-up","addictions au wake-up"},
				{"addiction au yayo","addictions au yayo"},
				{"agarilux","agarilux"},
				{"agave","agaves"},
				{"agneau","agneaux"},
				{"alocasia","alocasias"},
				{"alpaga","alpagas"},
				{"alphacastor","alphacastors"},
				{"alternateur de cycle circadien","alternateurs de cycle circadien"},
				{"ambroisie","ambroisies"},
				{"amplificateur psychique","amplificateurs psychiques"},
				{"âne","ânes"},
				{"ânesse","ânesses"},
				{"anesthésie","anesthésies"},
				{"annulaire droit","annulaires droits"},
				{"annulaire gauche","annulaires gauches"},
				{"ânon","ânons"},
				{"antenne","antennes"},
				{"antenne droite","antennes droites"},
				{"antenne gauche","antennes gauches"},
				{"apaisement dû au smokeleaf","apaisements dûs au smokeleaf"},
				{"apaisement dû au yayo","apaisements dûs au yayo"},
				{"arbre brûlé","arbres brûlés"},
				{"arbrisseau","arbrisseaux"},
				{"arc composite","arcs composites"},
				{"arc court","arcs courts"},
				{"archer","archers"},
				{"archère","archères"},
				{"archère lourde","archères lourdes"},
				{"archer lourd","archers lourds"},
				{"arc long","arcs longs"},
				{"ardoise","ardoises"},
				{"ardoise lissée","ardoises lissées"},
				{"argent","argents"},
				{"armature de vaisseau","armatures de vaisseau"},
				{"armature de vaisseau (plan)","armatures de vaisseau (plan)"},
				{"arme à feu inachevée","armes à feu inachevées"},
				{"arme inachevée","armes inachevées"},
				{"armure de cataphracte","armures de cataphracte"},
				{"armure de commando","armures de commando"},
				{"armure de plates","armures de plates"},
				{"armure de reconnaissance","armures de reconnaissance"},
				{"armure inachevée","armures inachevées"},
				{"artefact de folie","artefacts de folie"},
				{"artefact de perturbation psychique","artefacts de perturbation psychique"},
				{"artefact d'impulsion animale","artefacts d'impulsion animale"},
				{"artefact d'impulsion calmante","artefacts d'impulsion calmante"},
				{"assembleur de mécanoïdes","assembleurs de mécanoïdes"},
				{"assistant circadien","assistants circadiens"},
				{"assistant d'apprentissage","assistants d'apprentissage"},
				{"asthme","asthmes"},
				{"astragale","astragales"},
				{"astronaute","astronautes"},
				{"astronaute hostile","astronautes hostiles"},
				{"atelier de fabrication","ateliers de fabrication"},
				{"attaque cardiaque","attaques cardiaques"},
				{"auriculaire droit","auriculaires droits"},
				{"auriculaire gauche","auriculaires gauches"},
				{"aurore","aurores"},
				{"autruche","autruches"},
				{"avant-poste","avant-postes"},
				{"baie","baies"},
				{"balise de commerce orbital","balises de commerce orbital"},
				{"balise de commerce orbital (nouvel emplacement)","balises de commerce orbital (nouvel emplacement)"},
				{"balise de commerce orbital (plan)","balises de commerce orbital (plan)"},
				{"balise de débarquement pour vaisseau","balises de débarquement pour vaisseau"},
				{"balise de largage mécanoïde","balises de largage mécanoïde"},
				{"balle de canon à aiguille","balles de canon à aiguille"},
				{"balle de carabine de survie","balles de carabine de survie"},
				{"balle de fusil à impulsion","balles de fusil à impulsion"},
				{"balle de fusil à pompe","balles de fusil à pompe"},
				{"balle de fusil d'assaut","balles de fusil d'assaut"},
				{"balle de fusil de précision","balles de fusil de précision"},
				{"balle de lance-charges","balles de lance-charges"},
				{"balle de minigun","balles de minigun"},
				{"balle de mini-tourelle","balles de mini-tourelle"},
				{"balle de mitrailleuse","balles de mitrailleuse"},
				{"balle de pistolet automatique","balles de pistolet automatique"},
				{"balle de pistolet-mitrailleur","balles de pistolet-mitrailleur"},
				{"balle de pistolet-mitrailleur lourd","balles de pistolet-mitrailleur lourd"},
				{"balle de revolver","balles de revolver"},
				{"balle incendiaire","balles incendiaires"},
				{"bambou","bambous"},
				{"banc de fabrication","bancs de fabrication"},
				{"bande de pirates","bandes de pirates"},
				{"baril de fermentation","barils de fermentation"},
				{"baril de fermentation (plan)","barils de fermentation (plan)"},
				{"baron","barons"},
				{"baronne","baronnes"},
				{"barricade","barricades"},
				{"barrière de béton antique","barrières de béton antique"},
				{"base","bases"},
				{"base de faction","bases de faction"},
				{"base de faction abandonnée","bases de faction abandonnée"},
				{"base de faction détruite","bases de faction détruite"},
				{"base de raid","bases de raid"},
				{"bassin","bassins"},
				{"bassin hydroponique","bassins hydroponiques"},
				{"bassin hydroponique (plan)","bassins hydroponiques (plan)"},
				{"bâton de focalisation","bâtons de focalisation"},
				{"batterie","batteries"},
				{"batterie (nouvel emplacement)","batteries (nouvel emplacement)"},
				{"batterie (plan)","batteries (plan)"},
				{"bébé alpaga","bébés alpagas"},
				{"bébé alphacastor","bébés alphacastors"},
				{"bébé autruche","bébés autruches"},
				{"bébé boomalope","bébés boomalopes"},
				{"bébé capybara","bébés capybaras"},
				{"bébé caribou","bébés caribous"},
				{"bébé casoar","bébés casoars"},
				{"bébé chinchilla","bébés chinchillas"},
				{"bébé cobaye","bébés cobayes"},
				{"bébé cobra","bébés cobras"},
				{"bébé cougar","bébés cougars"},
				{"bébé dromadaire","bébés dromadaires"},
				{"bébé écureuil","bébés écureuils"},
				{"bébé émeu","bébés émeus"},
				{"bébé fennec","bébés fennecs"},
				{"bébé grizzly","bébés grizzlys"},
				{"bébé iguane","bébés iguanes"},
				{"bébé léopard","bébés léopards"},
				{"bébé lynx","bébés lynx"},
				{"bébé mégaraignée","bébés mégaraignées"},
				{"bébé mégascarabée","bébés mégascarabées"},
				{"bébé mégathérium","bébés mégathériums"},
				{"bébé panthère","bébés panthères"},
				{"bébé rataboum","bébés rataboums"},
				{"bébé raton laveur","bébés ratons laveurs"},
				{"bébé rhinocéros","bébés rhinocéros"},
				{"bébé spélopède","bébés spélopèdes"},
				{"bébé thrumbo","bébés thrumbos"},
				{"bébé tortue","bébés tortues"},
				{"bébé wapiti","bébés wapitis"},
				{"bec","becs"},
				{"bélier","béliers"},
				{"berserker","berserkers"},
				{"besoin en luciferium","besoins en luciferium"},
				{"biche","biches"},
				{"bière","bières"},
				{"bile","biles"},
				{"bionique inachevé","bioniques inachevés"},
				{"bison","bisons"},
				{"bisonne","bisonnes"},
				{"bisonneau","bisonneaux"},
				{"blaster de charge légère","blasters de charge légère"},
				{"blaster lourd","blasters lourds"},
				{"blessure","blessures"},
				{"blessure par balle","blessures par balle"},
				{"bloc d'ardoise","blocs d'ardoise"},
				{"bloc de calcaire","blocs de calcaire"},
				{"bloc de granite","blocs de granite"},
				{"bloc de grès","blocs de grès"},
				{"bloc de marbre","blocs de marbre"},
				{"bloquage des artères","bloquages des artères"},
				{"bois","bois"},
				{"bombardement","bombardements"},
				{"bonhomme de neige","bonhommes de neige"},
				{"bonnet","bonnets"},
				{"boomalope","boomalopes"},
				{"bosse","bosses"},
				{"bouc","boucs"},
				{"bouche","bouches"},
				{"bouclier anti-mortier","boucliers anti-mortier"},
				{"bouclier d'énergie","boucliers d'énergie"},
				{"bouclier pare-balles","boucliers pare-balles"},
				{"boue","boues"},
				{"bouleau","bouleaux"},
				{"bouquetin","bouquetins"},
				{"bouteille","bouteilles"},
				{"bovin","bovins"},
				{"box pour petits animaux","boxes pour petits animaux"},
				{"box pour petits animaux (nouvel emplacement)","boxes pour petits animaux (nouvel emplacement)"},
				{"box pour petits animaux (plan)","boxes pour petits animaux (plan)"},
				{"branche","branches"},
				{"bras","bras"},
				{"bras archotech","bras archotechs"},
				{"bras bionique","bras bioniques"},
				{"bras de forage","bras de forage"},
				{"bras droit","bras droits"},
				{"brasero","braseros"},
				{"bras gauche","bras gauches"},
				{"brebis","brebis"},
				{"brûlure","brûlures"},
				{"brûlure chimique","brûlures chimiques"},
				{"bryolux","bryolux"},
				{"bûche","bûches"},
				{"buisson","buissons"},
				{"buisson d'ambroisie","buissons d'ambroisie"},
				{"buisson de baies","buissons de baies"},
				{"câble électrique","câbles électriques"},
				{"câble électrique (plan)","câbles électriques (plan)"},
				{"cabri","cabris"},
				{"cacaoyer","cacaoyers"},
				{"cactus pelote-d'épingles","cactus pelotes-d'épingles"},
				{"cactus saguaro","cactus saguaros"},
				{"cadavre d'alpaga","cadavres d'alpaga"},
				{"cadavre d'alphacastor","cadavres d'alphacastor"},
				{"cadavre d'autruche","cadavres d'autruche"},
				{"cadavre de boomalope","cadavres de boomalope"},
				{"cadavre de bouquetin","cadavres de bouquetin"},
				{"cadavre de capybara","cadavres de capybara"},
				{"cadavre de caribou","cadavres de caribou"},
				{"cadavre de casoar","cadavres de casoar"},
				{"cadavre de centipède","cadavres de centipède"},
				{"cadavre de cerf","cadavres de cerf"},
				{"cadavre de chinchilla","cadavres de chinchilla"},
				{"cadavre de cobra","cadavres de cobra"},
				{"cadavre de cochon","cadavres de cochon"},
				{"cadavre de cougar","cadavres de cougar"},
				{"cadavre d'écureuil","cadavres d'écureuil"},
				{"cadavre de dinde","cadavres de dinde"},
				{"cadavre de dromadaire","cadavres de dromadaire"},
				{"cadavre de faucheur","cadavres de faucheur"},
				{"cadavre de fennec","cadavres de fennec"},
				{"cadavre de gazelle","cadavres de gazelle"},
				{"cadavre de grizzly","cadavres de grizzly"},
				{"cadavre de husky","cadavres de husky"},
				{"cadavre de labrador","cadavres de labrador"},
				{"cadavre de lancier","cadavres de lancier"},
				{"cadavre d'éléphant","cadavres d'éléphant"},
				{"cadavre de lièvre","cadavres de lièvre"},
				{"cadavre de lièvre des neiges","cadavres de lièvre des neiges"},
				{"cadavre de loup arctique","cadavres de loup arctique"},
				{"cadavre de loup des bois","cadavres de loup des bois"},
				{"cadavre de lynx","cadavres de lynx"},
				{"cadavre de mégaraignée","cadavres de mégaraignée"},
				{"cadavre de mégascarabée","cadavres de mégascarabée"},
				{"cadavre de mégathérium","cadavres de mégathérium"},
				{"cadavre d'émeu","cadavres d'émeu"},
				{"cadavre de muffalo","cadavres de muffalo"},
				{"cadavre de panthère","cadavres de panthère"},
				{"cadavre de poulet","cadavres de poulet"},
				{"cadavre de rat","cadavres de rat"},
				{"cadavre de rataboum","cadavres de rataboum"},
				{"cadavre de raton laveur","cadavres de raton laveur"},
				{"cadavre de renard arctique","cadavres de renard arctique"},
				{"cadavre de renard roux","cadavres de renard roux"},
				{"cadavre de rhinocéros","cadavres de rhinocéros"},
				{"cadavre de sanglier","cadavres de sanglier"},
				{"cadavre de singe","cadavres de singe"},
				{"cadavre de spélopède","cadavres de spélopède"},
				{"cadavre de thrumbo","cadavres de thrumbo"},
				{"cadavre de tortue","cadavres de tortue"},
				{"cadavre de vache","cadavres de vache"},
				{"cadavre de wapiti","cadavres de wapiti"},
				{"cadavre de warg","cadavres de warg"},
				{"cadavre de yorkshire terrier","cadavres de yorkshire terrier"},
				{"cadavre d'iguane","cadavres d'iguane"},
				{"cadavre d'ours polaire","cadavres d'ours polaire"},
				{"cadavre d'un chat","cadavres d'un chat"},
				{"cadavre humain","cadavres humains"},
				{"cage thoracique","cages thoraciques"},
				{"caisse à outils","caisses à outils"},
				{"caisse à outils (nouvel emplacement)","caisses à outils (nouvel emplacement)"},
				{"caisse à outils (plan)","caisses à outils (plan)"},
				{"caisson d'hypersommeil","caissons d'hypersommeil"},
				{"caisson d'hypersommeil antique","caissons d'hypersommeil antique"},
				{"caisson d'hypersommeil (plan)","caissons d'hypersommeil (plan)"},
				{"calcaire","calcaires"},
				{"calcaire lissé","calcaires lissés"},
				{"camp de bandits","camps de bandits"},
				{"camp de prisonniers","camps de prisonniers"},
				{"canard","canards"},
				{"cane","canes"},
				{"caneton","canetons"},
				{"canetonne","canetonnes"},
				{"canon","canons"},
				{"canon à aiguilles","canons à aiguilles"},
				{"canon automatique","canons automatiques"},
				{"canon de mini-tourelle","canons de mini-tourelle"},
				{"canon de précision","canons de précision"},
				{"canon incendiaire","canons incendiaires"},
				{"canon inferno","canons infernos"},
				{"capitaine","capitaines"},
				{"capsule de largage","capsules de largage"},
				{"capsule de largage (en approche)","capsules de largage (en approche)"},
				{"capsule de largage (en partance)","capsules de largage (en partance)"},
				{"capsule de transport","capsules de transport"},
				{"capsule de transport (plan)","capsules de transport (plan)"},
				{"capsule d'hypersommeil","capsules d'hypersommeil"},
				{"capsule d'hypersommeil (plan)","capsules d'hypersommeil (plan)"},
				{"capteur","capteurs"},
				{"capteur auditif","capteurs auditifs"},
				{"capteur olfactif","capteurs olfactifs"},
				{"capteur optique droit","capteurs optiques droits"},
				{"capteur optique gauche","capteurs optiques gauches"},
				{"capteur (plan)","capteurs (plan)"},
				{"capteur sonore droit","capteurs sonores droits"},
				{"capteur sonore gauche","capteurs sonores gauches"},
				{"capteur visuel","capteurs visuels"},
				{"capybara","capybaras"},
				{"carabine de survie","carabines de survie"},
				{"carapace","carapaces"},
				{"caravane","caravanes"},
				{"caravane attaquée","caravanes attaquées"},
				{"carbu-réacteur infini","carbu-réacteurs infinis"},
				{"carbu-réacteur infini (plan)","carbu-réacteurs infinis (plan)"},
				{"carcinome","carcinomes"},
				{"caribou","caribous"},
				{"carrelage en acier (plan)","carrelages en acier (plan)"},
				{"carrelage en acier (sol)","carrelages en acier (sol)"},
				{"carrelage en ardoise (plan)","carrelages en ardoise (plan)"},
				{"carrelage en ardoise (sol)","carrelages en ardoise (sol)"},
				{"carrelage en argent (plan)","carrelages en argent (plan)"},
				{"carrelage en argent (sol)","carrelages en argent (sol)"},
				{"carrelage en calcaire (plan)","carrelages en calcaire (plan)"},
				{"carrelage en calcaire (sol)","carrelages en calcaire (sol)"},
				{"carrelage en granite (plan)","carrelages en granite (plan)"},
				{"carrelage en granite (sol)","carrelages en granite (sol)"},
				{"carrelage en grès (plan)","carrelages en grès (plan)"},
				{"carrelage en grès (sol)","carrelages en grès (sol)"},
				{"carrelage en marbre (plan)","carrelages en marbre (plan)"},
				{"carrelage en marbre (sol)","carrelages en marbre (sol)"},
				{"carrelage en or (plan)","carrelages en or (plan)"},
				{"carrelage en or (sol)","carrelages en or (sol)"},
				{"carrelage stérile (plan)","carrelages stériles (plan)"},
				{"carrelage stérile (sol)","carrelages stériles (sol)"},
				{"casoar","casoars"},
				{"casque de cataphracte","casques de cataphracte"},
				{"casque de commando","casques de commando"},
				{"casque de reconnaissance","casques de reconnaissance"},
				{"casque d'optimisation psychique","casques d'optimisation psychique"},
				{"casque renforcé","casques renforcés"},
				{"casque simple","casques simples"},
				{"cataphractaire","cataphractaires"},
				{"cataphracte","cataphractes"},
				{"cataracte","cataractes"},
				{"cecropia","cecropias"},
				{"ceinture à fumigènes","ceintures à fumigènes"},
				{"ceinture inachevée","ceintures inachevées"},
				{"cellule de puissance instable","cellules de puissance instable"},
				{"cendre","cendres"},
				{"centipède","centipèdes"},
				{"centipède mécanoïde","centipèdes mécanoïdes"},
				{"cerf","cerfs"},
				{"cerveau","cerveaux"},
				{"cerveau artificiel","cerveaux artificiels"},
				{"chair humaine","chairs humaines"},
				{"chaise","chaises"},
				{"chaise (nouvel emplacement)","chaises (nouvel emplacement)"},
				{"chaise (plan)","chaises (plan)"},
				{"champ iem","champs iem"},
				{"champignon cru","champignons crus"},
				{"champion","champions"},
				{"championne","championnes"},
				{"chapeau de cowboy","chapeaux de cowboy"},
				{"chapeau de dames","chapeaux de dames"},
				{"chapeau melon","chapeaux melons"},
				{"chapeau papier psychique","chapeaux papiers psychiques"},
				{"charge de blaster lourd","charges de blaster lourd"},
				{"chasseur","chasseurs"},
				{"chasseuse","chasseuses"},
				{"chat","chats"},
				{"chaton","chatons"},
				{"chatonne","chatonnes"},
				{"chatte","chattes"},
				{"chef","chefs"},
				{"chef berserker","chefs berserkers"},
				{"cheffe","cheffes"},
				{"chemfuel","chemfuels"},
				{"chemise","chemises"},
				{"chemise à volants","chemises à volants"},
				{"chemise d'optimisation psychique","chemises d'optimisation psychique"},
				{"chêne","chênes"},
				{"cheval","chevaux"},
				{"chevalier","chevaliers"},
				{"chèvre","chèvres"},
				{"chevreau","chevreaux"},
				{"chevrette","chevrettes"},
				{"chinchilla","chinchillas"},
				{"chiot husky","chiots huskys"},
				{"chiot labrador","chiots labradors"},
				{"chiot warg","chiots wargs"},
				{"chiot yorkshire terrier","chiots yorkshire terriers"},
				{"choc cérébral","chocs cérébraux"},
				{"chocolat","chocolats"},
				{"choc psychique","chocs psychiques"},
				{"cibleur orbital mécanoïde","cibleurs orbitaux mécanoïdes"},
				{"cinquième anneau corporel","cinquièmes anneaux corporels"},
				{"cinquième griffe de la patte arrière droite","cinquièmes griffes de la patte arrière droite"},
				{"cinquième griffe de la patte arrière gauche","cinquièmes griffes de la patte arrière gauche"},
				{"cinquième griffe de la patte avant droite","cinquièmes griffes de la patte avant droite"},
				{"cinquième griffe de la patte avant gauche","cinquièmes griffes de la patte avant gauche"},
				{"cirrhose","cirrhoses"},
				{"citoyen impérial","citoyens impériaux"},
				{"citoyenne impériale","citoyennes impériales"},
				{"clavecin","clavecins"},
				{"clavicule","clavicules"},
				{"clavicule droite","clavicules droites"},
				{"clavicule gauche","clavicules gauches"},
				{"climatiseur","climatiseurs"},
				{"climatiseur (plan)","climatiseurs (plan)"},
				{"clivia","clivias"},
				{"coagulateur","coagulateurs"},
				{"cobaye","cobayes"},
				{"cobra","cobras"},
				{"cochon","cochons"},
				{"cocktail molotov","cocktails molotov"},
				{"cœur","cœurs"},
				{"cœur bionique","cœurs bioniques"},
				{"coiffe tribale","coiffes tribales"},
				{"colon","colons"},
				{"colonne","colonnes"},
				{"colonne vertébrale","colonnes vertébrales"},
				{"colonne vertébrale bionique","colonnes vertébrales bioniques"},
				{"coma catatonique","comas catatoniques"},
				{"commerçant","commerçants"},
				{"commerçant de la ville","commerçants de la ville"},
				{"commerçante","commerçantes"},
				{"commerçante impériale","commerçantes impériales"},
				{"commerçant impérial","commerçants impériaux"},
				{"commode","commodes"},
				{"commode (nouvel emplacement)","commodes (nouvel emplacement)"},
				{"commode (plan)","commodes (plan)"},
				{"communauté d'étrangers belliqueux","communautés d'étrangers belliqueux"},
				{"communauté d'étrangers pacifiques","communautés d'étrangers pacifiques"},
				{"composant","composants"},
				{"composant avancé","composants avancés"},
				{"composant inachevé","composants inachevés"},
				{"comte","comtes"},
				{"comtesse","comtesses"},
				{"conduit étanche","conduits étanches"},
				{"conduit étanche (plan)","conduits étanches (plan)"},
				{"console de communication","consoles de communication"},
				{"console de communication (plan)","consoles de communication (plan)"},
				{"consul","consuls"},
				{"consule","consules"},
				{"contrôleur météo","contrôleurs météos"},
				{"contusion","contusions"},
				{"coq","coqs"},
				{"coquelet","coquelets"},
				{"corne","cornes"},
				{"corne de thrumbo","cornes de thrumbo"},
				{"corne frontale","cornes frontales"},
				{"corps","corps"},
				{"corset","corsets"},
				{"cou","cous"},
				{"cougar","cougars"},
				{"coup de lame","coups de lame"},
				{"couronne","couronnes"},
				{"couteau","couteaux"},
				{"cracheur de fumée","cracheurs de fumée"},
				{"cracheur toxique","cracheurs toxiques"},
				{"crâne","crânes"},
				{"crochet à venin","crochets à venin"},
				{"croc acéré","crocs acérés"},
				{"croc à venin","crocs à venin"},
				{"croquette","croquettes"},
				{"crosse","crosses"},
				{"cuir","cuirs"},
				{"cuirasse","cuirasses"},
				{"cuir de cochon","cuirs de cochon"},
				{"cuir de dromadaire","cuirs de dromadaire"},
				{"cuir d'éléphant","cuirs d'éléphant"},
				{"cuir de lézard","cuirs de lézard"},
				{"cuir de rhinocéros","cuirs de rhinocéros"},
				{"cuir d'oiseau","cuirs d'oiseau"},
				{"cuir fin","cuirs fins"},
				{"cuisinière à bois","cuisinières à bois"},
				{"cuisinière à bois (plan)","cuisinières à bois (plan)"},
				{"cuisinière électrique","cuisinières électriques"},
				{"cuisinière électrique (plan)","cuisinières électriques (plan)"},
				{"cyprès","cyprès"},
				{"daguet","daguets"},
				{"dallage en béton (plan)","dallages en béton (plan)"},
				{"dallage en béton (sol)","dallages en béton (sol)"},
				{"dame","dames"},
				{"débris","débris"},
				{"débris d'acier","débris d'acier"},
				{"débris de vaisseau","débris de vaisseau"},
				{"débris de vaisseau (en approche)","débris de vaisseau (en approche)"},
				{"déchet","déchets"},
				{"déchirure","déchirures"},
				{"déclencheur","déclencheurs"},
				{"déclencheur non chargé","déclencheurs non chargés"},
				{"décombre","décombres"},
				{"défense","défenses"},
				{"défense d'éléphant","défenses d'éléphant"},
				{"défense droite","défenses droites"},
				{"défense gauche","défenses gauches"},
				{"défenseur stellaire","défenseurs stellaires"},
				{"défoliateur","défoliateurs"},
				{"démence","démences"},
				{"dentier","dentiers"},
				{"dent","dents"},
				{"dérèglement climatique","dérèglements climatiques"},
				{"destructeur de planète","destructeurs de planète"},
				{"deuxième anneau corporel","deuxièmes anneaux corporels"},
				{"deuxième griffe de la patte arrière droite","deuxièmes griffes de la patte arrière droite"},
				{"deuxième griffe de la patte arrière gauche","deuxièmes griffes de la patte arrière gauche"},
				{"deuxième griffe de la patte avant droite","deuxièmes griffes de la patte avant droite"},
				{"deuxième griffe de la patte avant gauche","deuxièmes griffes de la patte avant gauche"},
				{"diabétoffe","diabétoffes"},
				{"diabledeau","diabledeaux"},
				{"dinde","dindes"},
				{"dindon","dindons"},
				{"dindonneau","dindonneaux"},
				{"dispositif dissolvant post-mortem","dispositifs dissolvants post-mortem"},
				{"distributeur de pâte nutritive","distributeurs de pâte nutritive"},
				{"distributeur de pâte nutritive (plan)","distributeurs de pâte nutritive (plan)"},
				{"doigt","doigts"},
				{"dompte-venin","dompte-venin"},
				{"double lieu de couchage","doubles lieux de couchage"},
				{"double lieu de couchage (plan)","doubles lieux de couchage (plan)"},
				{"dragonnier","dragonniers"},
				{"dri","dris"},
				{"dromadaire","dromadaires"},
				{"dromadaire juvénile","dromadaires juvéniles"},
				{"drone psychique","drones psychiques"},
				{"duc","ducs"},
				{"duchesse","duchesses"},
				{"dynamo iem","dynamos iem"},
				{"éclipse","éclipses"},
				{"écrasement","écrasements"},
				{"écureuil","écureuils"},
				{"écuyer","écuyers"},
				{"écuyère","écuyères"},
				{"effondrement de pierres","effondrements de pierres"},
				{"éléphant","éléphants"},
				{"éléphante","éléphantes"},
				{"éléphanteau","éléphanteaux"},
				{"élytre","élytres"},
				{"élytre droite","élytres droites"},
				{"élytre gauche","élytres gauches"},
				{"émanateur psychique","émanateurs psychiques"},
				{"émanateur psychique (plan)","émanateurs psychiques (plan)"},
				{"embuscade","embuscades"},
				{"émeu","émeus"},
				{"empire brisé","empires brisés"},
				{"empoisonnement","empoisonnements"},
				{"engelure","engelures"},
				{"énorme stèle","énormes stèles"},
				{"éolienne","éoliennes"},
				{"éolienne (plan)","éoliennes (plan)"},
				{"épaule","épaules"},
				{"épaule droite","épaules droites"},
				{"épaule droite mécanique","épaules droites mécaniques"},
				{"épaule gauche","épaules gauches"},
				{"épée longue","épées longues"},
				{"épée mono-moléculaire","épées mono-moléculaires"},
				{"épée mono-moléculaire liée","épées mono-moléculaires liées"},
				{"épée plasmique","épées plasmiques"},
				{"épée plasmique liée","épées plasmiques liées"},
				{"érable","érables"},
				{"erreur chirurgicale","erreurs chirurgicales"},
				{"éruption solaire","éruptions solaires"},
				{"esclave","esclaves"},
				{"escouade mécanoïde","escouades mécanoïdes"},
				{"estomac","estomacs"},
				{"estomac amélioré","estomacs améliorés"},
				{"estomac bionique","estomacs bioniques"},
				{"estomac détoxifiant","estomacs détoxifiants"},
				{"estomac nucléaire","estomacs nucléaires"},
				{"établi d'assemblage","établis d'assemblage"},
				{"établi d'assemblage (plan)","établis d'assemblage (plan)"},
				{"établi de boucher","établis de boucher"},
				{"établi de boucher (plan)","établis de boucher (plan)"},
				{"établi de brassage","établis de brassage"},
				{"établi de brassage (plan)","établis de brassage (plan)"},
				{"établi de fabrication (plan)","établis de fabrication (plan)"},
				{"établi de forgeron à combustible","établis de forgeron à combustible"},
				{"établi de forgeron à combustible (plan)","établis de forgeron à combustible (plan)"},
				{"établi de forgeron électrique","établis de forgeron électrique"},
				{"établi de forgeron électrique (plan)","établis de forgeron électrique (plan)"},
				{"établi de sculpture","établis de sculpture"},
				{"établi de sculpture (plan)","établis de sculpture (plan)"},
				{"établi de tailleur de pierre","établis de tailleur de pierre"},
				{"établi de tailleur de pierre (plan)","établis de tailleur de pierre (plan)"},
				{"établi de tissage électrique","établis de tissage électrique"},
				{"établi de tissage électrique (plan)","établis de tissage électrique (plan)"},
				{"établi de tissage manuel","établis de tissage manuel"},
				{"établi de tissage manuel (plan)","établis de tissage manuel (plan)"},
				{"étagère","étagères"},
				{"étagère (nouvel emplacement)","étagères (nouvel emplacement)"},
				{"étagère (plan)","étagères (plan)"},
				{"étagne","étagnes"},
				{"étalon","étalons"},
				{"étincelle","étincelles"},
				{"étranger","étrangers"},
				{"étranger en noir","étrangers en noir"},
				{"exhausteur d'amour","exhausteurs d'amour"},
				{"explosion","explosions"},
				{"extincteur à mousse","extincteurs à mousse"},
				{"extincteur à mousse (nouvel emplacement)","extincteurs à mousse (nouvel emplacement)"},
				{"extincteur à mousse (plan)","extincteurs à mousse (plan)"},
				{"faisceau d'énergie","faisceaux d'énergie"},
				{"faon","faons"},
				{"faon gazelle","faons gazelles"},
				{"faonne","faonnes"},
				{"faonne gazelle","faonnes gazelles"},
				{"faucheur","faucheurs"},
				{"fauteuil","fauteuils"},
				{"fauteuil (nouvel emplacement)","fauteuils (nouvel emplacement)"},
				{"fauteuil (plan)","fauteuils (plan)"},
				{"femme en noir","femmes en noir"},
				{"femme sauvage","femmes sauvages"},
				{"fémur","fémurs"},
				{"fémur droit","fémurs droits"},
				{"fémur gauche","fémurs gauches"},
				{"fennec","fennecs"},
				{"feu","feux"},
				{"feu de camp","feux de camp"},
				{"feu de camp (plan)","feux de camp (plan)"},
				{"feuille de psychoïde","feuilles de psychoïde"},
				{"feuille de smokeleaf","feuilles de smokeleaf"},
				{"flake","flakes"},
				{"flaque de chemfuel","flaques de chemfuel"},
				{"flèche","flèches"},
				{"flèche d'arc composite","flèches d'arc composite"},
				{"focalisateur de faisceau d'énergie orbital","focalisateurs de faisceau d'énergie orbital"},
				{"foie","foies"},
				{"foin","foins"},
				{"fonderie électrique","fonderies électriques"},
				{"fonderie électrique (plan)","fonderies électriques (plan)"},
				{"forage en profondeur","forages en profondeur"},
				{"forage en profondeur (plan)","forages en profondeur (plan)"},
				{"foret","forets"},
				{"four crématoire électrique","fours crématoires électriques"},
				{"four crématoire électrique (plan)","fours crématoires électriques (plan)"},
				{"fourrure bleue","fourrures bleues"},
				{"fourrure de chien","fourrures de chien"},
				{"fourrure de chinchilla","fourrures de chinchilla"},
				{"fourrure de cobaye","fourrures de cobaye"},
				{"fourrure de loup","fourrures de loup"},
				{"fourrure de panthère","fourrures de panthère"},
				{"fourrure de renard","fourrures de renard"},
				{"fourrure de thrumbo","fourrures de thrumbo"},
				{"fourrure d'ours","fourrures d'ours"},
				{"fourrure épaisse","fourrures épaisses"},
				{"fracture","fractures"},
				{"fragilité","fragilités"},
				{"fruit d'agave","fruits d'agave"},
				{"fumée","fumées"},
				{"fusil à impulsion","fusils à impulsion"},
				{"fusil à pompe","fusils à pompe"},
				{"fusil à pompe automatique","fusils à pompe automatique"},
				{"fusil d'assaut","fusils d'assaut"},
				{"fusil de précision","fusils de précision"},
				{"garde","gardes"},
				{"gardienne stellaire","gardiennes stellaires"},
				{"gardien stellaire","gardiens stellaires"},
				{"gastro-analyseur","gastro-analyseurs"},
				{"gazelle","gazelles"},
				{"gazelle juvénile","gazelles juvéniles"},
				{"gelée d'insecte","gelées d'insecte"},
				{"générateur à bois","générateurs à bois"},
				{"générateur à bois (plan)","générateurs à bois (plan)"},
				{"générateur de tornade","générateurs de tornade"},
				{"générateur géothermique","générateurs géothermiques"},
				{"générateur géothermique (plan)","générateurs géothermiques (plan)"},
				{"générateur hydroélectrique","générateurs hydroélectriques"},
				{"générateur hydroélectrique (plan)","générateurs hydroélectriques (plan)"},
				{"génisse","génisses"},
				{"génisse muffalo","génisses muffalos"},
				{"geyser","geysers"},
				{"gilet pare-balles","gilets pare-balles"},
				{"gisement de ressources précieuses","gisements de ressources précieuses"},
				{"glaive","glaives"},
				{"glande blindante","glandes blindantes"},
				{"glande d'armure","glandes d'armure"},
				{"glande durcissante","glandes durcissantes"},
				{"glume lumineuse","glumes lumineuses"},
				{"glume lumineuse (plan)","glumes lumineuses (plan)"},
				{"go-juice","go-juices"},
				{"goret","gorets"},
				{"gorette","gorettes"},
				{"goulot","goulots"},
				{"gouverneure stellaire","gouverneures stellaires"},
				{"gouverneur stellaire","gouverneurs stellaires"},
				{"grande sculpture","grandes sculptures"},
				{"grande sculpture (plan)","grandes sculptures (plan)"},
				{"grande stèle","grandes stèles"},
				{"grand trône","grands trônes"},
				{"granite","granites"},
				{"granite lissé","granites lissés"},
				{"gravats en ardoise","gravats en ardoise"},
				{"gravats en calcaire","gravats en calcaire"},
				{"gravats en granite","gravats en granite"},
				{"gravats en grès","gravats en grès"},
				{"gravats en marbre","gravats en marbre"},
				{"gravats rocheux","gravats rocheux"},
				{"grenade à fragmentation","grenades à fragmentation"},
				{"grenade iem","grenades iem"},
				{"grenadier","grenadiers"},
				{"grenadière","grenadières"},
				{"grenadière - fumigène","grenadières - fumigènes"},
				{"grenadière - iem","grenadières - iem"},
				{"grenadier - fumigène","grenadiers - fumigènes"},
				{"grenadier - iem","grenadiers - iem"},
				{"grès","grès"},
				{"grès lissé","grès lissés"},
				{"griffe","griffes"},
				{"griffe arrière","griffes arrière"},
				{"griffe avant","griffes avant"},
				{"griffe droite","griffes droites"},
				{"griffe énergétique","griffes énergétiques"},
				{"griffe gauche","griffes gauches"},
				{"griffe venimeuse","griffes venimeuses"},
				{"griffure","griffures"},
				{"grippe","grippes"},
				{"grizzly","grizzlys"},
				{"gros orteil droit","gros orteils droits"},
				{"gros orteil gauche","gros orteils gauches"},
				{"grossesse","grossesses"},
				{"groupe de mécanoïdes endormis","groupes de mécanoïdes endormis"},
				{"groupe de tourelles","groupes de tourelles"},
				{"groupe électrogène","groupes électrogènes"},
				{"groupe électrogène (plan)","groupes électrogènes (plan)"},
				{"guenille de sauvage","guenilles de sauvage"},
				{"guenon","guenons"},
				{"guenuche","guenuches"},
				{"guerrier","guerriers"},
				{"guerrière","guerrières"},
				{"gueule de bois","gueules de bois"},
				{"gueule de bois psychique","gueules de bois psychique"},
				{"hache","haches"},
				{"hampe","hampes"},
				{"harmoniseur psychique","harmoniseurs psychiques"},
				{"harpe","harpes"},
				{"hase","hases"},
				{"hase des neiges","hases des neiges"},
				{"haut-de-forme","hauts-de-forme"},
				{"haute herbe","hautes herbes"},
				{"herbe à foin","herbes à foin"},
				{"herbe folle","herbes folles"},
				{"herbe médicinale","herbes médicinales"},
				{"hiver volcanique","hivers volcaniques"},
				{"homme en noir","hommes en noir"},
				{"homme sauvage","hommes sauvages"},
				{"houblon","houblons"},
				{"humain","humains"},
				{"humérus","humérus"},
				{"humérus droit","humérus droits"},
				{"humérus gauche","humérus gauches"},
				{"husky","huskys"},
				{"hyperfibre","hyperfibres"},
				{"hypothermie","hypothermies"},
				{"iguane","iguanes"},
				{"iguane juvénile","iguanes juvéniles"},
				{"ikwa","ikwas"},
				{"impérial","impériaux"},
				{"implant analgésique","implants analgésiques"},
				{"implant de discrétion psychique","implants de discrétion psychique"},
				{"implant du bonheur","implants du bonheur"},
				{"index droit","index droits"},
				{"index gauche","index gauches"},
				{"indigène","indigènes"},
				{"infection","infections"},
				{"insecte","insectes"},
				{"insolation","insolations"},
				{"instrument de musique inachevé","instruments de musique inachevés"},
				{"interrupteur","interrupteurs"},
				{"interrupteur (plan)","interrupteurs (plan)"},
				{"intoxication alimentaire","intoxications alimentaires"},
				{"ivresse","ivresses"},
				{"jade","jades"},
				{"jambe","jambes"},
				{"jambe antérieure droit","jambes antérieures droits"},
				{"jambe antérieure gauche","jambes antérieures gauches"},
				{"jambe archotech","jambes archotechs"},
				{"jambe bionique","jambes bioniques"},
				{"jambe de bois","jambes de bois"},
				{"jambe droite","jambes droites"},
				{"jambe gauche","jambes gauches"},
				{"jambe postérieure droit","jambes postérieures droits"},
				{"jambe postérieure gauche","jambes postérieures gauches"},
				{"janissaire","janissaires"},
				{"jars","jars"},
				{"jeu de crocs à venin","jeux de crocs à venin"},
				{"jeu du lancer de cailloux","jeux du lancer de cailloux"},
				{"jeu du lancer de cailloux (nouvel emplacement)","jeux du lancer de cailloux (nouvel emplacement)"},
				{"jeu du lancer de cailloux (plan)","jeux du lancer de cailloux (plan)"},
				{"jeune alpaga","jeunes alpagas"},
				{"jeune alphacastor","jeunes alphacastors"},
				{"jeune autruche","jeunes autruches"},
				{"jeune biche","jeunes biches"},
				{"jeune boomalope","jeunes boomalopes"},
				{"jeune bouquetin","jeunes bouquetins"},
				{"jeune bovin","jeunes bovins"},
				{"jeune capybara","jeunes capybaras"},
				{"jeune caribou","jeunes caribous"},
				{"jeune casoar","jeunes casoars"},
				{"jeune chat","jeunes chats"},
				{"jeune chatte","jeunes chattes"},
				{"jeune chinchilla","jeunes chinchillas"},
				{"jeune cobaye","jeunes cobayes"},
				{"jeune cobra","jeunes cobras"},
				{"jeune cochon","jeunes cochons"},
				{"jeune cougar","jeunes cougars"},
				{"jeune dinde","jeunes dindes"},
				{"jeune dindon","jeunes dindons"},
				{"jeune écureuil","jeunes écureuils"},
				{"jeune éléphant","jeunes éléphants"},
				{"jeune éléphante","jeunes éléphantes"},
				{"jeune émeu","jeunes émeus"},
				{"jeune étagne","jeunes étagnes"},
				{"jeune fennec","jeunes fennecs"},
				{"jeune grizzly","jeunes grizzlys"},
				{"jeune guenon","jeunes guenons"},
				{"jeune hase","jeunes hases"},
				{"jeune hase des neiges","jeunes hases des neiges"},
				{"jeune husky","jeunes huskys"},
				{"jeune labrador","jeunes labradors"},
				{"jeune laie","jeunes laies"},
				{"jeune léopard","jeunes léopards"},
				{"jeune lièvre","jeunes lièvres"},
				{"jeune lièvre des neiges","jeunes lièvres des neiges"},
				{"jeune loup des bois","jeunes loups des bois"},
				{"jeune loup arctique","jeunes loups arctiques"},
				{"jeune louve arctique","jeunes louves arctiques"},
				{"jeune louve des bois","jeunes louves des bois"},
				{"jeune lynx","jeunes lynx"},
				{"jeune mégaraignée","jeunes mégaraignées"},
				{"jeune mégascarabée","jeunes mégascarabées"},
				{"jeune mégathérium","jeunes mégathériums"},
				{"jeune ourse polaire","jeunes ourses polaires"},
				{"jeune ours polaire","jeunes ours polaires"},
				{"jeune panthère","jeunes panthères"},
				{"jeune poulet","jeunes poulets"},
				{"jeune rat","jeunes rats"},
				{"jeune rataboum","jeunes rataboums"},
				{"jeune rate","jeunes rates"},
				{"jeune raton laveur","jeunes ratons laveurs"},
				{"jeune renard arctique","jeunes renards arctiques"},
				{"jeune renarde arctique","jeunes renardes arctiques"},
				{"jeune renard roux","jeunes renards roux"},
				{"jeune renarde rousse","jeunes renardes rousses"},
				{"jeune sanglier","jeunes sangliers"},
				{"jeune singe","jeunes singes"},
				{"jeune spélopède","jeunes spélopèdes"},
				{"jeune thrumbo","jeunes thrumbos"},
				{"jeune tortue","jeunes tortues"},
				{"jeune wapiti","jeunes wapitis"},
				{"jeune warg","jeunes wargs"},
				{"jeune yorkshire terrier","jeunes yorkshire terriers"},
				{"joint de smokeleaf","joints de smokeleaf"},
				{"joue","joues"},
				{"jouissance due au flake","jouissances dues au flake"},
				{"jouissance due au thé pekoe","jouissances dues au thé pekoe"},
				{"jument","juments"},
				{"laboratoire chimique","laboratoires chimiques"},
				{"laboratoire chimique (plan)","laboratoires chimiques (plan)"},
				{"labrador","labradors"},
				{"laie","laies"},
				{"laine d'alpaga","laines d'alpaga"},
				{"laine de bison","laines de bison"},
				{"laine de mégathérium","laines de mégathérium"},
				{"laine de mouton","laines de mouton"},
				{"laine de muffalo","laines de muffalo"},
				{"lait","laits"},
				{"lame","lames"},
				{"lame de coude","lames de coude"},
				{"lame droite","lames droites"},
				{"lame gauche","lames gauches"},
				{"lampadaire","lampadaires"},
				{"lampadaire (bleu)","lampadaires (bleu)"},
				{"lampadaire (bleu) (nouvel emplacement)","lampadaires (bleu) (nouvel emplacement)"},
				{"lampadaire (bleu) (plan)","lampadaires (bleu) (plan)"},
				{"lampadaire (nouvel emplacement)","lampadaires (nouvel emplacement)"},
				{"lampadaire (plan)","lampadaires (plan)"},
				{"lampadaire (rouge)","lampadaires (rouge)"},
				{"lampadaire (rouge) (nouvel emplacement)","lampadaires (rouge) (nouvel emplacement)"},
				{"lampadaire (rouge) (plan)","lampadaires (rouge) (plan)"},
				{"lampadaire (vert)","lampadaires (vert)"},
				{"lampadaire (vert) (nouvel emplacement)","lampadaires (vert) (nouvel emplacement)"},
				{"lampadaire (vert) (plan)","lampadaires (vert) (plan)"},
				{"lampe horticole","lampes horticoles"},
				{"lampe horticole (nouvel emplacement)","lampes horticoles (nouvel emplacement)"},
				{"lampe horticole (plan)","lampes horticoles (plan)"},
				{"lance","lances"},
				{"lance-charges","lance-charges"},
				{"lance-grenades à fragmentation","lance-grenades à fragmentation"},
				{"lance-grenades iem","lance-grenades iem"},
				{"lanceur de cocktails molotov","lanceurs de cocktails molotov"},
				{"lance-roquettes apocalyptique","lance-roquettes apocalyptiques"},
				{"lance-roquettes triple","lance-roquettes triples"},
				{"lanceur de balles incendiaires","lanceurs de balles incendiaires"},
				{"lanceur de capsules","lanceurs de capsules"},
				{"lanceur de capsules (plan)","lanceurs de capsules (plan)"},
				{"lanceur de fumigène","lanceurs de fumigène"},
				{"lanceur de mini-projectiles","lanceurs de mini-projectiles"},
				{"lanceur iem","lanceurs iem"},
				{"lancier","lanciers"},
				{"lecteur psychique","lecteurs psychiques"},
				{"léopard","léopards"},
				{"lésion chimique moyenne","lésions chimiques moyennes"},
				{"lésion chimique sévère","lésions chimiques sévères"},
				{"levraut","levrauts"},
				{"levraut des neiges","levrauts des neiges"},
				{"lieu d'assemblage","lieux d'assemblage"},
				{"lieu d'assemblage (plan)","lieux d'assemblage (plan)"},
				{"lieu de couchage","lieux de couchage"},
				{"lieu de couchage pour animaux","lieux de couchage pour animaux"},
				{"lieu de dépeçage","lieux de dépeçage"},
				{"lieu de dépeçage (plan)","lieux de dépeçage (plan)"},
				{"lièvre","lièvres"},
				{"lièvre des neiges","lièvres des neiges"},
				{"liquide amniotique","liquides amniotiques"},
				{"lit","lits"},
				{"lit double","lits doubles"},
				{"lit double (nouvel emplacement)","lits doubles (nouvel emplacement)"},
				{"lit double (plan)","lits doubles (plan)"},
				{"lit médicalisé","lits médicalisés"},
				{"lit médicalisé (nouvel emplacement)","lits médicalisés (nouvel emplacement)"},
				{"lit médicalisé (plan)","lits médicalisés (plan)"},
				{"lit (nouvel emplacement)","lits (nouvel emplacement)"},
				{"lit (plan)","lits (plan)"},
				{"lit pour animaux","lits pour animaux"},
				{"lit pour animaux (nouvel emplacement)","lits pour animaux (nouvel emplacement)"},
				{"lit pour animaux (plan)","lits pour animaux (plan)"},
				{"lit royal","lits royaux"},
				{"lit royal (nouvel emplacement)","lits royaux (nouvel emplacement)"},
				{"lit royal (plan)","lits royaux (plan)"},
				{"loup arctique","loups arctiques"},
				{"loup des bois","loups des bois"},
				{"louve arctique","louves arctiques"},
				{"louve des bois","louves des bois"},
				{"louveteau arctique","louveteaux arctiques"},
				{"louveteau des bois","louveteaux des bois"},
				{"luciferium","luciferium"},
				{"lumbago","lumbagos"},
				{"lynx","lynx"},
				{"lys","lys"},
				{"machinerie compactée","machineries compactées"},
				{"mâchoire","mâchoires"},
				{"magasin","magasins"},
				{"main","mains"},
				{"main droite","mains droites"},
				{"main en bois","mains en bois"},
				{"main gauche","mains gauches"},
				{"main griffue","mains griffues"},
				{"main verte","mains vertes"},
				{"maïs","maïs"},
				{"majeur droit","majeurs droits"},
				{"majeur gauche","majeurs gauches"},
				{"maladie d'alzheimer","maladies d'alzheimer"},
				{"maladie du sommeil","maladies du sommeil"},
				{"malaria","malarias"},
				{"mal de la résurrection","maux de la résurrection"},
				{"mal du caisson","maux du caisson"},
				{"malnutrition","malnutritions"},
				{"manche","manches"},
				{"mandataire","mandataires"},
				{"mandibule","mandibules"},
				{"manteau","manteaux"},
				{"marbre","marbres"},
				{"marbre lissé","marbres lissés"},
				{"marcassin","marcassins"},
				{"marchand","marchands"},
				{"marchande","marchandes"},
				{"marche","marches"},
				{"marqueur","marqueurs"},
				{"marqueur de monument","marqueurs de monument"},
				{"marteau de guerre","marteaux de guerre"},
				{"marteau de zeus","marteaux de zeus"},
				{"marteau de zeus lié","marteaux de zeus liés"},
				{"masque de guerre","masques de guerre"},
				{"masse","masses"},
				{"massue","massues"},
				{"mécanite fibreuse","mécanites fibreuses"},
				{"mécanite sensorielle","mécanites sensorielles"},
				{"mécanoïde","mécanoïdes"},
				{"mech-sérum de résurrection","mech-sérums de résurrection"},
				{"mech-sérum guérisseur","mech-sérums guérisseurs"},
				{"médicament","médicaments"},
				{"médicament avancé","médicaments avancés"},
				{"mégaraignée","mégaraignées"},
				{"mégascarabée","mégascarabées"},
				{"mégathérium","mégathériums"},
				{"membre","membres"},
				{"mercenaire - cogneur","mercenaires - cogneurs"},
				{"mercenaire - cogneuse","mercenaires - cogneuses"},
				{"mercenaire d'élite","mercenaires d'élite"},
				{"mercenaire lourd","mercenaires lourds"},
				{"mercenaire lourde","mercenaires lourdes"},
				{"mercenaire - mitrailleur","mercenaires - mitrailleurs"},
				{"mercenaire - mitrailleuse","mercenaires - mitrailleuses"},
				{"mercenaire - sniper","mercenaires - snipers"},
				{"métal compacté","métaux compactés"},
				{"météo non naturelle","météos non naturelles"},
				{"météorite (en approche)","météorites (en approche)"},
				{"meute de chasseurs d'hommes","meutes de chasseurs d'hommes"},
				{"mignonnes petites dents","mignonnes petites dents"},
				{"mildiou","mildious"},
				{"minerai d'argent","minerais d'argent"},
				{"minerai d'or","minerais d'or"},
				{"minerai d'uranium","minerais d'uranium"},
				{"minigun","miniguns"},
				{"mini-projectile","mini-projectiles"},
				{"mini-tourelle","mini-tourelles"},
				{"mini-tourelle (construction)","mini-tourelles (construction)"},
				{"mini-tourelle (plan)","mini-tourelles (plan)"},
				{"mitrailleuse","mitrailleuses"},
				{"modificateur corporel","modificateurs corporels"},
				{"modificateur de climat","modificateurs de climat"},
				{"modification climatique","modifications climatiques"},
				{"moniteur de signes vitaux","moniteurs de signes vitaux"},
				{"moniteur de signes vitaux (nouvel emplacement)","moniteurs de signes vitaux (nouvel emplacement)"},
				{"moniteur de signes vitaux (plan)","moniteurs de signes vitaux (plan)"},
				{"moquette bleue (plan)","moquettes bleues (plan)"},
				{"moquette bleue (sol)","moquettes bleues (sol)"},
				{"moquette crème (plan)","moquettes crèmes (plan)"},
				{"moquette crème (sol)","moquettes crèmes (sol)"},
				{"moquette noire (plan)","moquettes noires (plan)"},
				{"moquette noire (sol)","moquettes noires (sol)"},
				{"moquette rouge (plan)","moquettes rouges (plan)"},
				{"moquette rouge (sol)","moquettes rouges (sol)"},
				{"moquette verte (plan)","moquettes vertes (plan)"},
				{"moquette verte (sol)","moquettes vertes (sol)"},
				{"morceau de vaisseau spatial (en approche)","morceaux de vaisseau spatial (en approche)"},
				{"morceau empoisonné de vaisseau écrasé","morceaux empoisonnés de vaisseau écrasé"},
				{"morsure","morsures"},
				{"mortier","mortiers"},
				{"mortier automatique","mortiers automatiques"},
				{"mortier (construction)","mortiers (construction)"},
				{"mortier (nouvel emplacement)","mortiers (nouvel emplacement)"},
				{"mortier (plan)","mortiers (plan)"},
				{"mote","motes"},
				{"mousse","mousses"},
				{"mousse anti-incendie","mousses anti-incendie"},
				{"moût","moûts"},
				{"mouton","moutons"},
				{"muffalo","muffalos"},
				{"muffalo juvénile","muffalos juvéniles"},
				{"multi-analyseur","multi-analyseurs"},
				{"multi-analyseur (nouvel emplacement)","multi-analyseurs (nouvel emplacement)"},
				{"multi-analyseur (plan)","multi-analyseurs (plan)"},
				{"mur","murs"},
				{"mur (plan)","murs (plan)"},
				{"narine","narines"},
				{"navette","navettes"},
				{"navette (entrante)","navettes (entrante)"},
				{"navette (partante)","navettes (partante)"},
				{"neurocalculateur","neurocalculateurs"},
				{"neutroamine","neutroamines"},
				{"névrose de résurrection","névroses de résurrection"},
				{"nez","nez"},
				{"nez esthétique","nez esthétiques"},
				{"nid","nids"},
				{"noble","nobles"},
				{"nouveau arrivant","nouveaux arrivants"},
				{"nouvelle tribu","nouvelles tribus"},
				{"noyau central de l'ordinateur de bord","noyaux centraux de l'ordinateur de bord"},
				{"noyau central de l'ordinateur de bord (plan)","noyaux centraux de l'ordinateur de bord (plan)"},
				{"noyau central d'ordinateur de bord","noyaux centraux d'ordinateur de bord"},
				{"noyau ia de personnalité","noyaux ia de personnalité"},
				{"noyau ia pédagogique","noyaux ia pédagogiques"},
				{"nuage de fumée géant","nuages de fumée géant"},
				{"obus à impulsion électromagnétique","obus à impulsion électromagnétique"},
				{"obus anti-incendie","obus anti-incendie"},
				{"obus d'autocanon","obus d'autocanon"},
				{"obus en uranium","obus en uranium"},
				{"obus hautement explosif","obus hautement explosifs"},
				{"obus incendiaire","obus incendiaires"},
				{"obus pour lanceur de fumigène","obus pour lanceur de fumigène"},
				{"obus pour lanceur iem","obus pour lanceur iem"},
				{"occultateur solaire","occultateurs solaires"},
				{"œil","yeux"},
				{"œil archotech","yeux archotechs"},
				{"œil bionique","yeux bioniques"},
				{"œil droit","yeux droits"},
				{"œil gauche","yeux gauches"},
				{"œuf d'autruche (fécondé)","œufs d'autruche (fécondé)"},
				{"œuf de canard (fécondé)","œufs de canard (fécondé)"},
				{"œuf de canard (non fécondé)","œufs de canard (non fécondé)"},
				{"œuf de casoar (fécondé)","œufs de casoar (fécondé)"},
				{"œuf de cobra (fécondé)","œufs de cobra (fécondé)"},
				{"œuf de dinde (fécondé)","œufs de dinde (fécondé)"},
				{"œuf d'émeu (fécondé)","œufs d'émeu (fécondé)"},
				{"œuf de poule (fécondé)","œufs de poule (fécondé)"},
				{"œuf de poule (non fécondé)","œufs de poule (non fécondé)"},
				{"œuf de tortue (fécondé)","œufs de tortue (fécondé)"},
				{"œuf d'iguane (fécondé)","œufs d'iguane (fécondé)"},
				{"œuf d'oie (fécondé)","œufs d'oie (fécondé)"},
				{"œuf d'oie (non fécondé)","œufs d'oie (non fécondé)"},
				{"ogive à antimatière","ogives à antimatière"},
				{"oie","oies"},
				{"oiseau","oiseaux"},
				{"oison","oisons"},
				{"onde psychique","ondes psychiques"},
				{"onde psychique apaisante","ondes psychiques apaisantes"},
				{"or","ors"},
				{"orage","orages"},
				{"oreille","oreilles"},
				{"oreille bionique","oreilles bioniques"},
				{"oreille droite","oreilles droites"},
				{"oreille gauche","oreilles gauches"},
				{"orteil","orteils"},
				{"ourse polaire","ourses polaires"},
				{"oursonne polaire","oursonnes polaires"},
				{"ourson polaire","oursons polaires"},
				{"ours polaire","ours polaires"},
				{"overdose de drogue","overdoses de drogue"},
				{"palmier","palmiers"},
				{"panneau solaire","panneaux solaires"},
				{"panneau solaire (plan)","panneaux solaires (plan)"},
				{"pantalon","pantalons"},
				{"pantalon renforcé","pantalons renforcés"},
				{"panthère","panthères"},
				{"parasite musculaire","parasites musculaires"},
				{"parka","parkas"},
				{"parquet (plan)","parquets (plan)"},
				{"parquet (sol)","parquets (sol)"},
				{"particule","particules"},
				{"partie de vaisseau (défoliateur)","parties de vaisseau (défoliateur)"},
				{"partie de vaisseau (drone psychique)","parties de vaisseau (drone psychique)"},
				{"partie du corps manquante","parties du corps manquante"},
				{"patchwork","patchworks"},
				{"pâte nutritive","pâtes nutritives"},
				{"patte","pattes"},
				{"patte arrière droite","pattes arrière droites"},
				{"patte arrière gauche","pattes arrière gauches"},
				{"patte avant droite","pattes avant droites"},
				{"patte avant gauche","pattes avant gauches"},
				{"patte centrale droite","pattes centrales droites"},
				{"patte centrale gauche","pattes centrales gauches"},
				{"patte droite","pattes droites"},
				{"patte gauche","pattes gauches"},
				{"pavement en ardoise (plan)","pavements en ardoise (plan)"},
				{"pavement en ardoise (sol)","pavements en ardoise (sol)"},
				{"pavement en béton (plan)","pavements en béton (plan)"},
				{"pavement en béton (sol)","pavements en béton (sol)"},
				{"pavement en calcaire (plan)","pavements en calcaire (plan)"},
				{"pavement en calcaire (sol)","pavements en calcaire (sol)"},
				{"pavement en granite (plan)","pavements en granite (plan)"},
				{"pavement en granite (sol)","pavements en granite (sol)"},
				{"pavement en grès (plan)","pavements en grès (plan)"},
				{"pavement en grès (sol)","pavements en grès (sol)"},
				{"pavement en marbre (plan)","pavements en marbre (plan)"},
				{"pavement en marbre (sol)","pavements en marbre (sol)"},
				{"peau humaine","peaux humaines"},
				{"pemmican","pemmican"},
				{"pénitent","pénitents"},
				{"pénitente","pénitentes"},
				{"penoxycyline","penoxycylines"},
				{"perte d'audition","pertes d'audition"},
				{"perte de sang","pertes de sang"},
				{"peste","pestes"},
				{"petite couronne","petites couronnes"},
				{"petite sculpture","petites sculptures"},
				{"petite sculpture (plan)","petites sculptures (plan)"},
				{"petit orteil droit","petits orteils droits"},
				{"petit orteil gauche","petits orteils gauches"},
				{"peuplier","peupliers"},
				{"piano","pianos"},
				{"piano inachevé","pianos inachevés"},
				{"pic de genou","pics de genou"},
				{"pied","pieds"},
				{"pied antérieur droit","pieds antérieurs droits"},
				{"pied antérieur gauche","pieds antérieurs gauches"},
				{"pied-brillant","pieds-brillants"},
				{"pied droit","pieds droits"},
				{"pied en bois","pieds en bois"},
				{"pied gauche","pieds gauches"},
				{"pied postérieur droit","pieds postérieurs droits"},
				{"pied postérieur gauche","pieds postérieurs gauches"},
				{"piège à antimatière improvisé","pièges à antimatière improvisés"},
				{"piège à antimatière improvisé (plan)","pièges à antimatière improvisés (plan)"},
				{"piège anti-incendie improvisé","pièges anti-incendie improvisés"},
				{"piège anti-incendie improvisé (plan)","pièges anti-incendie improvisés (plan)"},
				{"piège à pointes","pièges à pointes"},
				{"piège explosif improvisé","pièges explosifs improvisés"},
				{"piège explosif improvisé (plan)","pièges explosifs improvisés (plan)"},
				{"piège iem improvisé","pièges iem improvisés"},
				{"piège iem improvisé (plan)","pièges iem improvisés (plan)"},
				{"piège incendiaire improvisé","pièges incendiaires improvisés"},
				{"piège incendiaire improvisé (plan)","pièges incendiaires improvisés (plan)"},
				{"pierres empilées","pierres empilées"},
				{"pile vanométrique","piles vanométriques"},
				{"pile vanométrique (plan)","piles vanométriques (plan)"},
				{"pillard","pillards"},
				{"pillarde","pillardes"},
				{"pilum","pila"},
				{"pilum (lancé)","pila (lancé)"},
				{"pin","pins"},
				{"piquet de fer à cheval","piquets de fer à cheval"},
				{"piquet de fer à cheval (nouvel emplacement)","piquets de fer à cheval (nouvel emplacement)"},
				{"piquet de fer à cheval (plan)","piquets de fer à cheval (plan)"},
				{"piquier","piquiers"},
				{"pirate","pirates"},
				{"pissenlit","pissenlits"},
				{"pistolet automatique","pistolets automatiques"},
				{"pistolet-mitrailleur","pistolets-mitrailleurs"},
				{"pistolet-mitrailleur lourd","pistolets-mitrailleurs lourds"},
				{"planque","planques"},
				{"plant de coton","plants de coton"},
				{"plant de fraisier","plants de fraisier"},
				{"plant de houblon","plants de houblon"},
				{"plant de maïs","plants de maïs"},
				{"plant de plante psychoïde","plants de plante psychoïde"},
				{"plant de pommes de terre","plants de pommes de terre"},
				{"plant de riz","plants de riz"},
				{"plant de smokeleaf","plants de smokeleaf"},
				{"plastacier","plastaciers"},
				{"plastacier compacté","plastaciers compactés"},
				{"plateau de jeu d'ur","plateaux de jeu d'ur"},
				{"plateau de jeu d'ur (construction)","plateaux de jeu d'ur (construction)"},
				{"plateau de jeu d'ur (plan)","plateaux de jeu d'ur (plan)"},
				{"plat gastronomique","plats gastronomiques"},
				{"plat raffiné","plats raffinés"},
				{"plat simple","plats simples"},
				{"pluie toxique","pluies toxiques"},
				{"poignée","poignées"},
				{"poil de dromadaire","poils de dromadaire"},
				{"poing","poings"},
				{"poing droit","poings droits"},
				{"poing gauche","poings gauches"},
				{"pointe","pointes"},
				{"pomme de terre","pommes de terre"},
				{"pompe à eau","pompes à eau"},
				{"pompe à eau (plan)","pompes à eau (plan)"},
				{"pont (construction)","ponts (construction)"},
				{"pont (plan)","ponts (plan)"},
				{"porcelet","porcelets"},
				{"porte","portes"},
				{"porte automatique","portes automatiques"},
				{"porte automatique (plan)","portes automatiques (plan)"},
				{"porte (plan)","portes (plan)"},
				{"possible menace","possibles menaces"},
				{"poste basique de recherche","postes basiques de recherche"},
				{"poste basique de recherche (plan)","postes basiques de recherche (plan)"},
				{"poste hi-tech de recherche","postes hi-techs de recherche"},
				{"poste hi-tech de recherche (plan)","postes hi-techs de recherche (plan)"},
				{"pot de fleurs","pots de fleurs"},
				{"pot de fleurs (nouvel emplacement)","pots de fleurs (nouvel emplacement)"},
				{"pot de fleurs (plan)","pots de fleurs (plan)"},
				{"pouce droit","pouces droits"},
				{"pouce gauche","pouces gauches"},
				{"poulain","poulains"},
				{"poule","poules"},
				{"poulet","poulets"},
				{"poulette","poulettes"},
				{"poumon","poumons"},
				{"poumon droit","poumons droits"},
				{"poumon gauche","poumons gauches"},
				{"pourparler de paix","pourparlers de paix"},
				{"poussin","poussins"},
				{"premier anneau corporel","premiers anneaux corporels"},
				{"première griffe de la patte arrière droite","premières griffes de la patte arrière droite"},
				{"première griffe de la patte arrière gauche","premières griffes de la patte arrière gauche"},
				{"première griffe de la patte avant droite","premières griffes de la patte avant droite"},
				{"première griffe de la patte avant gauche","premières griffes de la patte avant gauche"},
				{"préteur","préteurs"},
				{"prétrice","prétrices"},
				{"processeur hydraulique","processeurs hydrauliques"},
				{"propulseur de vaisseau","propulseurs de vaisseau"},
				{"propulseur de vaisseau (plan)","propulseurs de vaisseau (plan)"},
				{"prothèse auditive","prothèses auditives"},
				{"prothèse cardiaque","prothèses cardiaques"},
				{"prothèse de bras","prothèses de bras"},
				{"prothèse de jambe","prothèses de jambe"},
				{"prothèse inachevée","prothèses inachevées"},
				{"prothorax","prothorax"},
				{"provocateur","provocateurs"},
				{"provocatrice","provocatrices"},
				{"quadrupède","quadrupèdes"},
				{"quartus droit","quartus droits"},
				{"quartus gauche","quartus gauches"},
				{"quatrième anneau corporel","quatrièmes anneaux corporels"},
				{"quatrième griffe de la patte arrière droite","quatrièmes griffes de la patte arrière droite"},
				{"quatrième griffe de la patte arrière gauche","quatrièmes griffes de la patte arrière gauche"},
				{"quatrième griffe de la patte avant droite","quatrièmes griffes de la patte avant droite"},
				{"quatrième griffe de la patte avant gauche","quatrièmes griffes de la patte avant gauche"},
				{"queue","queues"},
				{"racine de vie","racines de vie"},
				{"racine de vie sauvage","racines de vie sauvage"},
				{"radiateur","radiateurs"},
				{"radiateur (plan)","radiateurs (plan)"},
				{"radius","radius"},
				{"radius droit","radius droits"},
				{"radius gauche","radius gauches"},
				{"raffinerie","raffineries"},
				{"raffinerie (construction)","raffineries (construction)"},
				{"raffinerie (plan)","raffineries (plan)"},
				{"rafflesia géante","rafflesias géantes"},
				{"ralentissement hypothermique","ralentissements hypothermiques"},
				{"rat","rats"},
				{"rataboum","rataboums"},
				{"rate","rates"},
				{"ration de survie","rations de survie"},
				{"raton","ratons"},
				{"ratonne","ratonnes"},
				{"raton laveur","ratons laveurs"},
				{"réacteur","réacteurs"},
				{"réacteur de vaisseau","réacteurs de vaisseau"},
				{"réacteur de vaisseau (plan)","réacteurs de vaisseau (plan)"},
				{"refroidisseur passif","refroidisseurs passifs"},
				{"refroidisseur passif (plan)","refroidisseurs passifs (plan)"},
				{"réfugié abattu","réfugiés abattus"},
				{"réfugié de l'espace","réfugiés de l'espace"},
				{"réfugiée de l'espace","réfugiées de l'espace"},
				{"rein","reins"},
				{"rein droit","reins droits"},
				{"rein gauche","reins gauches"},
				{"renard arctique","renards arctiques"},
				{"renarde arctique","renardes arctiques"},
				{"renardeau arctique","renardeaux arctiques"},
				{"renard roux","renards roux"},
				{"renarde rousse","renardes rousses"},
				{"renardeau roux","renardeaux roux"},
				{"représentant","représentants"},
				{"représentante","représentantes"},
				{"réservoir","réservoirs"},
				{"réservoir (plan)","réservoirs (plan)"},
				{"réverbère antique","réverbères antiques"},
				{"revolver","revolvers"},
				{"rhinocéros","rhinocéros"},
				{"rhinocéros juvénile","rhinocéros juvéniles"},
				{"rideaux","rideaux"},
				{"riz","riz"},
				{"robe d'optimisation psychique","robes d'optimisation psychique"},
				{"robe royale","robes royales"},
				{"roncier","ronciers"},
				{"roquette","roquettes"},
				{"roquette apocalyptique","roquettes apocalyptiques"},
				{"rose","roses"},
				{"ruche mécanoïde","ruches mécanoïdes"},
				{"sable","sables"},
				{"sabot","sabots"},
				{"sabot arrière droit","sabots arrière droits"},
				{"sabot arrière gauche","sabots arrière gauches"},
				{"sabot avant droit","sabots avant droits"},
				{"sabot avant gauche","sabots avant gauches"},
				{"sabot droit","sabots droits"},
				{"sabot gauche","sabots gauches"},
				{"sac de couchage","sacs de couchage"},
				{"sac de couchage double","sacs de couchage double"},
				{"sac de couchage double (nouvel emplacement)","sacs de couchage double (nouvel emplacement)"},
				{"sac de couchage double (plan)","sacs de couchage double (plan)"},
				{"sac de couchage (nouvel emplacement)","sacs de couchage (nouvel emplacement)"},
				{"sac de couchage (plan)","sacs de couchage (plan)"},
				{"sac de sable","sacs de sable"},
				{"sac de sable éventré","sacs de sable éventrés"},
				{"sac de sable (plan)","sacs de sable (plan)"},
				{"saleté","saletés"},
				{"saleté animale","saletés animales"},
				{"sang","sangs"},
				{"sang d'insecte","sangs d'insecte"},
				{"sanglier","sangliers"},
				{"sarcophage","sarcophages"},
				{"sarcophage (plan)","sarcophages (plan)"},
				{"saule pleureur","saules pleureurs"},
				{"scanner géologique","scanners géologiques"},
				{"scanner géologique à longue portée","scanners géologiques à longue portée"},
				{"scanner géologique à longue portée (plan)","scanners géologiques à longue portée (plan)"},
				{"scanner géologique (plan)","scanners géologiques (plan)"},
				{"scarabée","scarabées"},
				{"scarabée avec des pinces","scarabées avec des pinces"},
				{"sculpture","sculptures"},
				{"sculpture inachevée","sculptures inachevées"},
				{"sculpture monumentale","sculptures monumentales"},
				{"sculpture monumentale (plan)","sculptures monumentales (plan)"},
				{"secundus droit","secundus droits"},
				{"secundus gauche","secundus gauches"},
				{"sensibilisateur psychique","sensibilisateurs psychiques"},
				{"serpent","serpents"},
				{"signal action - embuscade","signaux actions - embuscades"},
				{"signal action - message","signaux actions - messages"},
				{"singe","singes"},
				{"singeteau","singeteaux"},
				{"sixième anneau corporel","sixièmes anneaux corporels"},
				{"soldat","soldats"},
				{"soldat de l'espace","soldats de l'espace"},
				{"soldate","soldates"},
				{"soldate de l'espace","soldates de l'espace"},
				{"soleil occulté","soleils occultés"},
				{"spélopède","spélopèdes"},
				{"sternum","sternums"},
				{"stimulation à l'ambroisie","stimulations à l'ambroisie"},
				{"stimulation au go-juice","stimulations au go-juice"},
				{"stimulation au luciferium","stimulations au luciferium"},
				{"stimulation au wake-up","stimulations au wake-up"},
				{"suppresseur psychique","suppresseurs psychiques"},
				{"suppression psychique","suppressions psychiques"},
				{"synthé","synthés"},
				{"système de visée de bombardement orbital","systèmes de visée de bombardement orbital"},
				{"table (1x2)","tables (1x2)"},
				{"table (1x2) (nouvel emplacement)","tables (1x2) (nouvel emplacement)"},
				{"table (1x2) (plan)","tables (1x2) (plan)"},
				{"table (2x2)","tables (2x2)"},
				{"table (2x2) (nouvel emplacement)","tables (2x2) (nouvel emplacement)"},
				{"table (2x2) (plan)","tables (2x2) (plan)"},
				{"table (2x4)","tables (2x4)"},
				{"table (2x4) (nouvel emplacement)","tables (2x4) (nouvel emplacement)"},
				{"table (2x4) (plan)","tables (2x4) (plan)"},
				{"table (3x3)","tables (3x3)"},
				{"table (3x3) (nouvel emplacement)","tables (3x3) (nouvel emplacement)"},
				{"table (3x3) (plan)","tables (3x3) (plan)"},
				{"table de billard","tables de billard"},
				{"table de billard (nouvel emplacement)","tables de billard (nouvel emplacement)"},
				{"table de billard (plan)","tables de billard (plan)"},
				{"table d'échecs","tables d'échecs"},
				{"table d'échecs (nouvel emplacement)","tables d'échecs (nouvel emplacement)"},
				{"table d'échecs (plan)","tables d'échecs (plan)"},
				{"table de nuit","tables de nuit"},
				{"table de nuit (nouvel emplacement)","tables de nuit (nouvel emplacement)"},
				{"table de nuit (plan)","tables de nuit (plan)"},
				{"table de poker","tables de poker"},
				{"table de poker (nouvel emplacement)","tables de poker (nouvel emplacement)"},
				{"table de poker (plan)","tables de poker (plan)"},
				{"tabouret","tabourets"},
				{"tabouret (nouvel emplacement)","tabourets (nouvel emplacement)"},
				{"tabouret (plan)","tabourets (plan)"},
				{"taillade","taillades"},
				{"taille","tailles"},
				{"taureau","taureaux"},
				{"taurillon","taurillons"},
				{"taurillon muffalo","taurillons muffalos"},
				{"teck","tecks"},
				{"télescope","télescopes"},
				{"télescope (nouvel emplacement)","télescopes (nouvel emplacement)"},
				{"télévision à écran géant","télévisions à écran géant"},
				{"télévision à écran géant (nouvel emplacement)","télévisions à écran géant (nouvel emplacement)"},
				{"télévision à écran plat","télévisions à écran plat"},
				{"télévision à écran plat (construction)","télévisions à écran plat (construction)"},
				{"télévision à écran plat (nouvel emplacement)","télévisions à écran plat (nouvel emplacement)"},
				{"télévision à écran plat (plan)","télévisions à écran plat (plan)"},
				{"télévision cathodique","télévisions cathodiques"},
				{"télévision cathodique (nouvel emplacement)","télévisions cathodiques (nouvel emplacement)"},
				{"télévision cathodique (plan)","télévisions cathodiques (plan)"},
				{"tenaille mentale","tenailles mentales"},
				{"terraformeur","terraformeurs"},
				{"tertius droit","tertius droits"},
				{"tertius gauche","tertius gauches"},
				{"tête","têtes"},
				{"thé pekoe","thés pekoe"},
				{"thorax","thorax"},
				{"thrumbo","thrumbos"},
				{"tibia","tibias"},
				{"tibia droit","tibias droits"},
				{"tibia gauche","tibias gauches"},
				{"tissu","tissus"},
				{"tolérance à l'alcool","tolérances à l'alcool"},
				{"tolérance à l'ambroisie","tolérances à l'ambroisie"},
				{"tolérance au go-juice","tolérances au go-juice"},
				{"tolérance au smokeleaf","tolérances au smokeleaf"},
				{"tolérance au wake-up","tolérances au wake-up"},
				{"tolérance au yayo","tolérances au yayo"},
				{"tombe","tombes"},
				{"tombe (plan)","tombes (plan)"},
				{"torche","torches"},
				{"torche (plan)","torches (plan)"},
				{"tornade","tornades"},
				{"torse","torses"},
				{"tortue","tortues"},
				{"tourelle autocanon","tourelles autocanons"},
				{"tourelle autocanon ( plan)","tourelles autocanons ( plan)"},
				{"tourelle blaster de charge automatique","tourelles blasters de charge automatique"},
				{"tourelle de lanceur de mini-projectiles","tourelles de lanceur de mini-projectiles"},
				{"tourelle de précision","tourelles de précision"},
				{"tourelle de tireur d'élite (plan)","tourelles de tireur d'élite (plan)"},
				{"tourelle inferno automatique","tourelles infernos automatiques"},
				{"tranchant","tranchants"},
				{"traumatisme","traumatismes"},
				{"tribu belliqueuse","tribus belliqueuses"},
				{"tribu indigène féroce","tribus indigènes féroces"},
				{"tribu indigène pacifique","tribus indigènes pacifiques"},
				{"troisième anneau corporel","troisièmes anneaux corporels"},
				{"troisième griffe de la patte arrière droite","troisièmes griffes de la patte arrière droite"},
				{"troisième griffe de la patte arrière gauche","troisièmes griffes de la patte arrière gauche"},
				{"troisième griffe de la patte avant droite","troisièmes griffes de la patte avant droite"},
				{"troisième griffe de la patte avant gauche","troisièmes griffes de la patte avant gauche"},
				{"tronc","troncs"},
				{"trône","trônes"},
				{"truie","truies"},
				{"t-shirt","t-shirts"},
				{"tunnel","tunnels"},
				{"uranium","uraniums"},
				{"urne","urnes"},
				{"vache","vaches"},
				{"vagabond","vagabonds"},
				{"vagabonde","vagabondes"},
				{"vague de chaleur","vagues de chaleur"},
				{"vague de froid","vagues de froid"},
				{"vaisseau spatial de secours","vaisseaux spatiaux de secours"},
				{"vase","vases"},
				{"veau","veaux"},
				{"veau muffalo","veaux muffalos"},
				{"veau yak","veaux yaks"},
				{"velle","velles"},
				{"velle muffalo","velles muffalos"},
				{"ventilation","ventilations"},
				{"ventilation (plan)","ventilations (plan)"},
				{"verrat","verrats"},
				{"ver intestinal","vers intestinaux"},
				{"veste","vestes"},
				{"veste d'optimisation psychique","vestes d'optimisation psychique"},
				{"veste renforcée","vestes renforcées"},
				{"veste royale","vestes royales"},
				{"vêtement inachevé","vêtements inachevés"},
				{"viande d'alpaga","viandes d'alpaga"},
				{"viande d'alphacastor","viandes d'alphacastor"},
				{"viande de bœuf","viandes de bœuf"},
				{"viande de boomalope","viandes de boomalope"},
				{"viande de bouquetin","viandes de bouquetin"},
				{"viande de capybara","viandes de capybara"},
				{"viande de caribou","viandes de caribou"},
				{"viande de cerf","viandes de cerf"},
				{"viande de chat","viandes de chat"},
				{"viande de chinchilla","viandes de chinchilla"},
				{"viande de cobra","viandes de cobra"},
				{"viande de cougar","viandes de cougar"},
				{"viande d'écureuil","viandes d'écureuil"},
				{"viande de dinde","viandes de dinde"},
				{"viande de dromadaire","viandes de dromadaire"},
				{"viande de gazelle","viandes de gazelle"},
				{"viande de husky","viandes de husky"},
				{"viande de labrador","viandes de labrador"},
				{"viande d'éléphant","viandes d'éléphant"},
				{"viande de lièvre","viandes de lièvre"},
				{"viande de loup","viandes de loup"},
				{"viande de lynx","viandes de lynx"},
				{"viande de mégathérium","viandes de mégathérium"},
				{"viande de muffalo","viandes de muffalo"},
				{"viande de panthère","viandes de panthère"},
				{"viande de porc","viandes de porc"},
				{"viande de poulet","viandes de poulet"},
				{"viande de rat","viandes de rat"},
				{"viande de rataboum","viandes de rataboum"},
				{"viande de raton laveur","viandes de raton laveur"},
				{"viande de renard","viandes de renard"},
				{"viande de rhinocéros","viandes de rhinocéros"},
				{"viande de singe","viandes de singe"},
				{"viande de thrumbo","viandes de thrumbo"},
				{"viande de tortue","viandes de tortue"},
				{"viande de wapiti","viandes de wapiti"},
				{"viande de warg","viandes de warg"},
				{"viande de yorkshire terrier","viandes de yorkshire terrier"},
				{"viande d'iguane","viandes d'iguane"},
				{"viande d'insecte ogm","viandes d'insecte ogm"},
				{"viande d'oiseau","viandes d'oiseau"},
				{"viande d'ours","viandes d'ours"},
				{"villageois","villageois"},
				{"villageoise","villageoises"},
				{"voile de guerre","voiles de guerre"},
				{"vomi","vomis"},
				{"wake-up","wake-ups"},
				{"wapiti","wapitis"},
				{"warg","wargs"},
				{"yak","yaks"},
				{"yayo","yayos"},
				{"yorkshire terrier","yorkshire terriers"},
				{"zone de chargement de la caravane","zones de chargement de la caravane"},
				{"zone de chargement de la caravane (plan)","zones de chargement de la caravane (plan)"},
				{"zone de fête","zones de fête"},
				{"zone de mariage","zones de mariage"}
			};

			// All exceptions will not be implemented: simply memorized the failed pluralization
			Dictionary<string, string> failed = new Dictionary<string, string>();

			foreach (var test in labels)
			{
				string str = test.Key;

				string str_pluralized = _lw.Pluralize(str, Verse.Gender.None) ;
				Console.WriteLine("test:" + str);

				if (str.Equals("granite lissé"))
				{
					int i = 1;
					i = i + 1;
				 }

				if (!str_pluralized.Equals(test.Value))
				{
					failed.Add(str, str_pluralized);
					Console.WriteLine("failed:" + str + " , " + str_pluralized + " (" + test.Value + ")");
				}
				Assert.AreEqual(test.Value, str_pluralized);
			}

			Assert.Zero(failed.Count);
		}
	}
}
